spring:
  application:
    name: movie-info-service
  webflux:
    base-path: /movies/api

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: ${spring.application.name}

movie-api:
  url: https://unelmamovie.com/api/v1
  token: 309|X3qhv5BB2zzgLHI1wWlLatv5uYgNwcJjdLaMa1GI


